### ISSUE TITLE
Problem loading PHP Generics in PhpStorm 2019.3.3

### ISSUE THREAD

**Issue by HenkPoley** [Haehnchen/idea-php-generics-plugin#10]
A red exclamation mark appears in the bottom right of PhpStorm, it reads:

```
com.intellij.diagnostic.PluginException: Short name 'ClassStringLocalInspection' is not unique
class 'de.espend.idea.php.generics.inspection.PsalmLocalImmutableInspection' in PluginDescriptor(name=PHP Generics, classpath=C:\Users\hjpol\.PhpStorm2019.3\config\plugins\PHP Generics)
and
class'de.espend.idea.php.generics.inspection.ClassStringLocalInspection' in PluginDescriptor(name=PHP Generics, classpath=C:\Users\hjpol\.PhpStorm2019.3\config\plugins\PHP Generics)
conflict [Plugin: de.espend.idea.php.generics]
	at com.intellij.codeInspection.ex.InspectionToolRegistrar.checkForDuplicateShortName(InspectionToolRegistrar.java:134)
	at com.intellij.codeInspection.ex.InspectionToolRegistrar.registerInspection(InspectionToolRegistrar.java:81)
	at com.intellij.codeInspection.ex.InspectionToolRegistrar.registerInspections(InspectionToolRegistrar.java:61)
	at com.intellij.codeInspection.ex.InspectionToolRegistrar.lambda$new$0(InspectionToolRegistrar.java:41)
	at com.intellij.openapi.util.NotNullLazyValue$2.compute(NotNullLazyValue.java:67)
	at com.intellij.openapi.util.NotNullLazyValue.getValue(NotNullLazyValue.java:38)
	at com.intellij.codeInspection.ex.InspectionToolRegistrar.createTools(InspectionToolRegistrar.java:174)
	at com.intellij.codeInspection.ex.InspectionProfileImpl.createTools(InspectionProfileImpl.java:459)
	at com.intellij.codeInspection.ex.InspectionProfileImpl.initialize(InspectionProfileImpl.java:481)
	at com.intellij.codeInspection.ex.NewInspectionProfile.initInspectionTools(InspectionProfile.kt:110)
	at com.intellij.codeInspection.ex.InspectionProfileImpl.initialize(InspectionProfileImpl.java:476)
	at com.intellij.codeInspection.ex.NewInspectionProfile.initInspectionTools(InspectionProfile.kt:110)
	at com.intellij.codeInspection.ex.NewInspectionProfile.initInspectionTools$default(InspectionProfile.kt:103)
	at com.intellij.codeInspection.ex.NewInspectionProfile.initInspectionTools(InspectionProfile.kt)
	at com.intellij.codeInspection.ex.InspectionProfileImpl.getAllTools(InspectionProfileImpl.java:770)
	at com.intellij.ide.ui.InspectionsTopHitProvider.getOptions(InspectionsTopHitProvider.java:31)
	at com.intellij.ide.ui.OptionsTopHitProvider.getCachedOptions(OptionsTopHitProvider.java:78)
	at com.intellij.ide.ui.OptionsTopHitProvider.access$600(OptionsTopHitProvider.java:39)
	at com.intellij.ide.ui.OptionsTopHitProvider$Activity.lambda$cacheAll$2(OptionsTopHitProvider.java:267)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.processWithPluginDescriptor(ExtensionPointImpl.java:292)
	at com.intellij.openapi.extensions.ExtensionPointName.processWithPluginDescriptor(ExtensionPointName.java:157)
	at com.intellij.ide.ui.OptionsTopHitProvider$Activity.cacheAll(OptionsTopHitProvider.java:263)
	at com.intellij.ide.ui.OptionsTopHitProvider$Activity.lambda$runActivity$0(OptionsTopHitProvider.java:248)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:222)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:30)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.execute(BoundedTaskExecutor.java:201)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:193)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by HenkPoley** [comment]
A trivial patch here that makes the short name non-unique: https://github.com/Haehnchen/idea-php-generics-plugin/pull/11

Hopefully that will make PHP Generics load properly.

(Edit: It may or may not be that PHP Generics "loads" and "does something useful", but I removed the plugin because PhpStorm was unhappy about it, and I didn't know where the new useful parts should show up in my editor)

**Comment by HenkPoley** [comment]
Small reminder that PHP Generics 0.3.0 from the plugin 'Marketplace' does not seem to load at all.

**Comment by alexbusu** [comment]
Another small reminder that PHP Generics 0.3.0 from the plugin 'Marketplace' does not seem to load at all.
Thanks!

**Comment by Haehnchen** [comment]
fixed
