### ISSUE TITLE
Got two java.lang.ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by b1rdex** [Haehnchen/idea-php-generics-plugin#20]
The first one:
```
java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
	at de.espend.idea.php.generics.type.TemplateAnnotationTypeProvider.complete(TemplateAnnotationTypeProvider.java:66)
	at com.jetbrains.php.PhpIndexImpl.lambda$completeType$1(PhpIndexImpl.java:129)
	at com.intellij.openapi.util.RecursionManager$1.doPreventingRecursion(RecursionManager.java:117)
	at com.jetbrains.php.PhpIndexImpl.completeType(PhpIndexImpl.java:129)
	at com.jetbrains.php.PhpIndexImpl.getClasses(PhpIndexImpl.java:708)
	at com.jetbrains.php.PhpIndexImpl.getBySignatureInternal(PhpIndexImpl.java:617)
	at com.jetbrains.php.PhpIndexImpl.getBySignature(PhpIndexImpl.java:508)
	at de.espend.idea.php.generics.utils.PhpTypeProviderUtil.getResolvedParameter(PhpTypeProviderUtil.java:159)
	at de.espend.idea.php.generics.utils.PhpTypeProviderUtil.getResolvedParameter(PhpTypeProviderUtil.java:136)
	at de.espend.idea.php.generics.type.TemplateAnnotationTypeProvider.getBySignature(TemplateAnnotationTypeProvider.java:103)
	at com.jetbrains.php.PhpIndexImpl.getBySignatureInternal(PhpIndexImpl.java:644)
	at com.jetbrains.php.PhpIndexImpl.getBySignature(PhpIndexImpl.java:508)
	at com.jetbrains.php.PhpIndexImpl.completeType(PhpIndexImpl.java:142)
	at com.jetbrains.php.PhpIndexImpl.completeType(PhpIndexImpl.java:100)
	at com.jetbrains.php.lang.psi.resolve.types.PhpType.global(PhpType.java:460)
	at com.jetbrains.php.completion.PhpLookupElement.getPhpType(PhpLookupElement.java:342)
	at com.jetbrains.php.completion.PhpCompletionSorting.getType(PhpCompletionSorting.java:551)
	at com.jetbrains.php.completion.PhpCompletionSorting.access$500(PhpCompletionSorting.java:56)
	at com.jetbrains.php.completion.PhpCompletionSorting$PhpReceiverTypeWeigher.weigh(PhpCompletionSorting.java:524)
	at com.jetbrains.php.completion.PhpCompletionSorting$PhpReceiverTypeWeigher.weigh(PhpCompletionSorting.java:503)
	at com.intellij.codeInsight.lookup.LookupElementWeigher.weigh(LookupElementWeigher.java:41)
	at com.intellij.codeInsight.lookup.CachingComparingClassifier.addElement(CachingComparingClassifier.java:76)
	at com.intellij.codeInsight.lookup.CachingComparingClassifier.addElement(CachingComparingClassifier.java:20)
	at com.intellij.codeInsight.lookup.Classifier.addElement(Classifier.java:40)
	at com.intellij.codeInsight.lookup.CachingComparingClassifier.addElement(CachingComparingClassifier.java:88)
	at com.intellij.codeInsight.lookup.CachingComparingClassifier.addElement(CachingComparingClassifier.java:20)
	at com.intellij.codeInsight.lookup.Classifier.addElement(Classifier.java:40)
	at com.intellij.codeInsight.lookup.CachingComparingClassifier.addElement(CachingComparingClassifier.java:88)
	at com.intellij.codeInsight.lookup.CachingComparingClassifier.addElement(CachingComparingClassifier.java:20)
	at com.intellij.codeInsight.lookup.Classifier.addElement(Classifier.java:40)
	at com.intellij.codeInsight.lookup.CachingComparingClassifier.addElement(CachingComparingClassifier.java:88)
	at com.intellij.codeInsight.lookup.CachingComparingClassifier.addElement(CachingComparingClassifier.java:20)
	at com.intellij.codeInsight.lookup.Classifier.addElement(Classifier.java:40)
	at com.intellij.codeInsight.lookup.CachingComparingClassifier.addElement(CachingComparingClassifier.java:88)
	at com.intellij.codeInsight.lookup.CachingComparingClassifier.addElement(CachingComparingClassifier.java:20)
	at com.intellij.codeInsight.lookup.Classifier.addElement(Classifier.java:40)
	at com.intellij.codeInsight.lookup.CachingComparingClassifier.addElement(CachingComparingClassifier.java:88)
	at com.intellij.codeInsight.lookup.CachingComparingClassifier.addElement(CachingComparingClassifier.java:20)
	at com.intellij.codeInsight.lookup.Classifier.addElement(Classifier.java:40)
	at com.intellij.codeInsight.lookup.CachingComparingClassifier.addElement(CachingComparingClassifier.java:88)
	at com.intellij.codeInsight.lookup.CachingComparingClassifier.addElement(CachingComparingClassifier.java:20)
	at com.intellij.codeInsight.completion.BaseCompletionLookupArranger.addElement(BaseCompletionLookupArranger.kt:129)
	at com.intellij.codeInsight.completion.CompletionLookupArrangerImpl.addElement(CompletionLookupArrangerImpl.java:26)
	at com.intellij.codeInsight.lookup.impl.LookupImpl.lambda$addItem$1(LookupImpl.java:276)
	at com.intellij.codeInsight.lookup.impl.LookupImpl.withLock(LookupImpl.java:1229)
	at com.intellij.codeInsight.lookup.impl.LookupImpl.addItem(LookupImpl.java:274)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator.addItemToLookup(CompletionProgressIndicator.java:452)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator.addItem(CompletionProgressIndicator.java:443)
	at com.intellij.codeInsight.completion.AsyncCompletion$1.lambda$null$0(CompletionThreading.java:145)
	at com.intellij.codeInsight.completion.AsyncCompletion.lambda$tryReadOrCancel$5(CompletionThreading.java:172)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1106)
	at com.intellij.codeInsight.completion.AsyncCompletion.tryReadOrCancel(CompletionThreading.java:170)
	at com.intellij.codeInsight.completion.AsyncCompletion$1.lambda$consume$1(CompletionThreading.java:145)
	at com.intellij.codeInsight.completion.AsyncCompletion$1WeighItems.run(CompletionThreading.java:113)
	at com.intellij.codeInsight.completion.AsyncCompletion.lambda$null$0(CompletionThreading.java:95)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:166)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:627)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:572)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:61)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:153)
	at com.intellij.codeInsight.completion.AsyncCompletion.lambda$startThread$1(CompletionThreading.java:91)
	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:20)
	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:11)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.call(ApplicationImpl.java:255)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

And the other one:
```
java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
	at de.espend.idea.php.generics.type.TemplateAnnotationTypeProvider.complete(TemplateAnnotationTypeProvider.java:66)
	at com.jetbrains.php.PhpIndexImpl.lambda$completeType$1(PhpIndexImpl.java:129)
	at com.intellij.openapi.util.RecursionManager$1.doPreventingRecursion(RecursionManager.java:117)
	at com.jetbrains.php.PhpIndexImpl.completeType(PhpIndexImpl.java:129)
	at com.jetbrains.php.PhpIndexImpl.completeType(PhpIndexImpl.java:100)
	at com.jetbrains.php.lang.psi.resolve.types.PhpType.global(PhpType.java:460)
	at com.jetbrains.php.lang.inspections.PhpVoidFunctionResultUsedInspection.analyzeCall(PhpVoidFunctionResultUsedInspection.java:50)
	at com.jetbrains.php.lang.inspections.PhpVoidFunctionResultUsedInspection.access$000(PhpVoidFunctionResultUsedInspection.java:23)
	at com.jetbrains.php.lang.inspections.PhpVoidFunctionResultUsedInspection$1.visitPhpMethodReference(PhpVoidFunctionResultUsedInspection.java:41)
	at com.jetbrains.php.lang.psi.elements.impl.MethodReferenceImpl.accept(MethodReferenceImpl.java:31)
	at com.intellij.codeInspection.InspectionEngine.acceptElements(InspectionEngine.java:69)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$null$6(LocalInspectionsPass.java:320)
	at com.intellij.util.AstLoadingFilter.lambda$toComputable$2(AstLoadingFilter.java:168)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:126)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:115)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:110)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$visitRestElementsAndCleanup$7(LocalInspectionsPass.java:320)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:149)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1106)
	at com.intellij.concurrency.ApplierCompleter.lambda$wrapInReadActionAndIndicator$1(ApplierCompleter.java:105)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:627)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:572)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:61)
	at com.intellij.concurrency.ApplierCompleter.wrapInReadActionAndIndicator(ApplierCompleter.java:117)
	at com.intellij.concurrency.ApplierCompleter.lambda$compute$0(ApplierCompleter.java:96)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:168)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:168)
	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:96)
	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
```

**Comment by Haehnchen** [comment]
fixed
