### ISSUE TITLE
PHPStan Feedback

### ISSUE THREAD

**Issue by shmax** [Haehnchen/idea-php-generics-plugin#29]
Hey there, [as promised](https://youtrack.jetbrains.com/issue/WI-35063#focus=streamItem-27-4117817.0-0) I've been checking out your phpstan plugin for PHPStorm, and overall I'm hugely impressed by what you've done. Bravo, sir. I think this could be a game-changer for us all.

All that said, I have some early feedback, if you're interested. Diving right in:

1. It would be nice to have some way to "build" the entire project. Currently, I have to run phpstan in a separate step and look up the files it finds, or just sort of meander randomly through my files looking for the error indicators. Could your tool be integrated into the "Code" menu?

2. Shouldn't the errors render little marks in the scroll gutter?
![image](https://user-images.githubusercontent.com/773172/80779125-8633a500-8b1f-11ea-9d87-aa228642012b.png)

3. I get the same error, constantly:

![image](https://user-images.githubusercontent.com/773172/80779196-bb3ff780-8b1f-11ea-997a-58730e259376.png)

I've clicked the "Exclude" link, and verified that it's added to the ignore list, but the error persists. Is there a more detailed log somewhere I can inspect?

I'll keep playing with it. More soon. Keep up the great work.

**Comment by Haehnchen** [comment]
1, 2.
Should work if the error is gone from 3. Its done continuously in background.

3. "I get the same error, constantly."
You can higher the timeout inside the "code quality settings", maybe just a skip idea to test it. What i am more wondering why phpstan is this slow. maybe you can reconfigure phpstan or update to  latest version. there were many approvments in caching and performance lately.

In background only the given file checked via PHPStan so it should be fast, i tested it also on bigger projects. I was wondering how it was performing there.
I am still open for implementation related to slow analysis, but i would prefer to handle it outside ;)

**Comment by shmax** [comment]
Ah, yes, increasing the wait timeout to 30s improved things a bit, but I still don't see any error indicators in the gutters. Also, sometimes I get java stack traces in the event log:

```
java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
	at de.espend.idea.php.generics.type.TemplateAnnotationTypeProvider.complete(TemplateAnnotationTypeProvider.java:66)
	at com.jetbrains.php.PhpIndexImpl.lambda$completeType$1(PhpIndexImpl.java:129)
	at com.intellij.openapi.util.RecursionManager$1.doPreventingRecursion(RecursionManager.java:117)
	at com.jetbrains.php.PhpIndexImpl.completeType(PhpIndexImpl.java:129)
	at com.jetbrains.php.PhpIndexImpl.completeType(PhpIndexImpl.java:100)
	at com.jetbrains.php.lang.psi.resolve.types.PhpType.global(PhpType.java:460)
	at com.jetbrains.php.completion.PhpLookupElement.renderElement(PhpLookupElement.java:235)
	at com.intellij.codeInsight.lookup.impl.LookupCellRenderer.lambda$getListCellRendererComponent$1(LookupCellRenderer.java:142)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:864)
	at com.intellij.codeInsight.lookup.impl.LookupCellRenderer.getListCellRendererComponent(LookupCellRenderer.java:139)
	at com.intellij.codeInsight.lookup.impl.LookupCellRenderer.getListCellRendererComponent(LookupCellRenderer.java:49)
	at com.intellij.ui.ExpandedItemListCellRendererWrapper.getListCellRendererComponent(ExpandedItemListCellRendererWrapper.java:24)
	at com.intellij.ui.components.WideSelectionListUI.paintCell(WideSelectionListUI.java:53)
	at java.desktop/javax.swing.plaf.basic.BasicListUI.paintImpl(BasicListUI.java:378)
	at java.desktop/javax.swing.plaf.basic.BasicListUI.paint(BasicListUI.java:301)
	at com.intellij.ui.components.WideSelectionListUI.paint(WideSelectionListUI.java:31)
	at java.desktop/javax.swing.plaf.ComponentUI.update(ComponentUI.java:161)
	at java.desktop/javax.swing.JComponent.paintComponent(JComponent.java:800)
	at com.intellij.ui.components.JBList.paintComponent(JBList.java:174)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1077)
	at com.intellij.ui.components.JBList.paint(JBList.java:106)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:910)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1086)
	at java.desktop/javax.swing.JViewport.paint(JViewport.java:737)
	at com.intellij.ui.components.JBViewport.paint(JBViewport.java:240)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:910)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1086)
	at java.desktop/javax.swing.JComponent.paintToOffscreen(JComponent.java:5263)
	at java.desktop/javax.swing.RepaintManager$PaintManager.paintDoubleBufferedImpl(RepaintManager.java:1654)
	at java.desktop/javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(RepaintManager.java:1629)
	at java.desktop/javax.swing.RepaintManager$PaintManager.paint(RepaintManager.java:1566)
	at java.desktop/javax.swing.RepaintManager.paint(RepaintManager.java:1333)
	at java.desktop/javax.swing.JComponent._paintImmediately(JComponent.java:5211)
	at java.desktop/javax.swing.JComponent.paintImmediately(JComponent.java:5021)
	at java.desktop/javax.swing.RepaintManager$4.run(RepaintManager.java:868)
	at java.desktop/javax.swing.RepaintManager$4.run(RepaintManager.java:851)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:851)
	at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:826)
	at java.desktop/javax.swing.RepaintManager.prePaintDirtyRegions(RepaintManager.java:775)
	at java.desktop/javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1901)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:974)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:847)
	at com.intellij.ide.IdeEventQueue.lambda$null$8(IdeEventQueue.java:449)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:741)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:448)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:492)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

Let me know if I can provide more information...

**Comment by dbalabka** [comment]
> 3. I get the same error, constantly:

Increasing the timeout helps. Right after Psalm create a cache error message disappear.

**Comment by shmax** [comment]
The max value for the timeout seems to be 30s, and I'm already maxed-out. And I'm not currently using Psalm.

**Comment by shmax** [comment]
With the latest version, I'm no longer getting the `ArrayIndexOutOfBoundsException`, so thank you. 👏
