### ISSUE TITLE
Plugin is not compatible with PhpStorm 2020.3

### ISSUE THREAD

**Issue by bzixilu** [Haehnchen/idea-php-generics-plugin#61]
Unfortunately, we've changed the API for quality tools in 2020.3, and the plugin stopped to be compatible. 

```
ExternalToolPass: 

com.intellij.diagnostic.PluginException: annotator: de.espend.idea.php.quality.phpstan.PhpStanAnnotatorQualityToolAnnotator@55928e4b (class de.espend.idea.php.quality.phpstan.PhpStanAnnotatorQualityToolAnnotator) [Plugin: de.espend.idea.php.generics]
	at com.intellij.ide.plugins.PluginManagerCore.createPluginException(PluginManagerCore.java:323)
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:12)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:59)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.process(ExternalToolPass.java:255)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.collectInformationWithProgress(ExternalToolPass.java:137)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:84)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:54)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$1(PassExecutorService.java:401)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1137)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:394)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:658)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:610)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:63)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:393)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:369)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:172)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:182)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:367)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:185)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: java.lang.AbstractMethodError: Missing implementation of resolved method 'abstract com.jetbrains.php.tools.quality.QualityToolType getQualityToolType()' of abstract class com.jetbrains.php.tools.quality.QualityToolAnnotator.
	at com.jetbrains.php.tools.quality.QualityToolAnnotator.collectAnnotatorInfo(QualityToolAnnotator.java:83)
	at com.jetbrains.php.tools.quality.QualityToolAnnotator.collectInformation(QualityToolAnnotator.java:137)
	at com.jetbrains.php.tools.quality.QualityToolAnnotator.collectInformation(QualityToolAnnotator.java:71)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.collectInformationWithProgress(ExternalToolPass.java:134)
	... 19 more
```

I'll open PR ASAP to restore compatibility with 2020.3. Sorry for the inconvenience!

**Comment by MaXal** [comment]
Since we implemented the support of PSalm/PHPStan as quality tools in-house for PhpStorm 2020.3 and your plugin is incompatible with this version. I will mark it as incompatible in the marketplace and list all its existing versions in our `disabled-plugin` list.
Probably this functionality should be removed/extracted into a separate plugin to avoid customers' confusion.
